<?php

namespace ContainerBjGtO5B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerfireProjService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.F1tB7lc.App\Controller\ApiController::fireProj()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.F1tB7lc'] ?? $container->load('get_ServiceLocator_F1tB7lcService'));

        if (isset($container->privates['.service_locator.F1tB7lc.App\\Controller\\ApiController::fireProj()'])) {
            return $container->privates['.service_locator.F1tB7lc.App\\Controller\\ApiController::fireProj()'];
        }

        return $container->privates['.service_locator.F1tB7lc.App\\Controller\\ApiController::fireProj()'] = $a->withContext('App\\Controller\\ApiController::fireProj()', $container);
    }
}
