<?php

namespace ContainerBjGtO5B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_VarDumper_CliDumperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'debug.var_dumper.cli_dumper' shared service.
     *
     * @return \Symfony\Component\VarDumper\Dumper\CliDumper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['debug.var_dumper.cli_dumper'] = new \Symfony\Component\VarDumper\Dumper\CliDumper();
    }
}
