<?php

namespace ContainerBjGtO5B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ApiPlatform_OpenapiService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.describers.api_platform.openapi' shared service.
     *
     * @return \ApiPlatform\OpenApi\OpenApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/openapi/Model/ExtensionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/openapi/OpenApi.php';

        return $container->privates['nelmio_api_doc.describers.api_platform.openapi'] = ($container->privates['api_platform.openapi.factory'] ?? $container->load('getApiPlatform_Openapi_FactoryService'))->__invoke();
    }
}
