<?php

namespace ContainerBjGtO5B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Swagger_Processor_MapQueryStringService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.swagger.processor.map_query_string' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Processor\MapQueryStringProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/Processor/MapQueryStringProcessor.php';

        return $container->privates['nelmio_api_doc.swagger.processor.map_query_string'] = new \Nelmio\ApiDocBundle\Processor\MapQueryStringProcessor();
    }
}
