version: '3.8'

services:
  ex-php:
    container_name: ex-php
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: docker
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      POSTGRES_DB: ${POSTGRES_DB:-ex}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
    volumes:
      - ./:/var/www/ex

  ex-nginx:
    image: nginx:latest
    container_name: ex-nginx
    restart: always
    depends_on:
      - ex-php
    ports:
      - "443:80"
    volumes:
      - ./:/var/www/ex
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ex}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: