<?php

namespace ContainerRxZjrbN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllercreateProjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bHSkjnx.App\Controller\ApiController::createProj()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bHSkjnx.App\\Controller\\ApiController::createProj()'] = ($container->privates['.service_locator.bHSkjnx'] ?? $container->load('get_ServiceLocator_BHSkjnxService'))->withContext('App\\Controller\\ApiController::createProj()', $container);
    }
}
