<?php

namespace ContainerRxZjrbN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeveloperControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WPvjtlV.App\Controller\DeveloperController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WPvjtlV'] ?? $container->load('get_ServiceLocator_WPvjtlVService'));

        if (isset($container->privates['.service_locator.WPvjtlV.App\\Controller\\DeveloperController::edit()'])) {
            return $container->privates['.service_locator.WPvjtlV.App\\Controller\\DeveloperController::edit()'];
        }

        return $container->privates['.service_locator.WPvjtlV.App\\Controller\\DeveloperController::edit()'] = $a->withContext('App\\Controller\\DeveloperController::edit()', $container);
    }
}
