<?php

namespace ContainerRxZjrbN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeveloper2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ni56v.G.App\Entity\Developer' shared service.
     *
     * @return \App\Entity\Developer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ni56v.G": it needs an instance of "App\\Entity\\Developer" but this type has been excluded in "config/services.yaml".');
    }
}
