<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBjGtO5B\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBjGtO5B/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBjGtO5B.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBjGtO5B\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBjGtO5B\App_KernelTestDebugContainer([
    'container.build_hash' => 'BjGtO5B',
    'container.build_id' => 'cca756d9',
    'container.build_time' => 1732401943,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBjGtO5B');
