<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxZjrbN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxZjrbN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxZjrbN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxZjrbN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxZjrbN\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxZjrbN',
    'container.build_id' => '19bcd686',
    'container.build_time' => 1732404198,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxZjrbN');
